#!/bin/bash 

function portFree {
  port=$1
  curl http://localhost:$port 2>&1 | grep -q Connection.refused
}

function launcher {
  port=$1
  name=$2
  shift; shift
  cmd="$*"

  if portFree $port; then true
  else
    echo == FATAL: cannot start $name: port $port in use.
    exit 1
  fi

  echo == starting $name

  $cmd & ID=$!

  trap "echo == killing $name; kill -9 $ID" EXIT

  echo waiting for port $port
  while portFree $port; do sleep 1; done
  echo started $name
}


GETH="/usr/local/bin/geth  --dev \
      --http.port ${PORT:=8545} \
      --nousb \
      --miner.gaslimit 12000000 \
      --http \
      --http.api personal,eth,net,web3,debug \
      --allow-insecure-unlock \
      --rpc.allow-unprotected-txs \
      --http.vhosts '*,localhost,host.docker.internal' \
      --http.corsdomain '*' \
      --http.addr "0.0.0.0" \
      --dev \
      --nodiscover --maxpeers 0 --mine \
      --miner.threads 1 \
      --verbosity 2 \
      --networkid ${NETWORKID:=1337} \
      --allow-insecure-unlock \
      --http \
      --verbosity 1 \
      --ignore-legacy-receipts"

launcher 8545 geth $GETH
launcher 3000 node "$@"
echo == started
sleep 1
