#!/bin/bash 

function fatal {
  echo "$@" 1>&2
  exit 1
}

function isPortFree {
  port=$1
  curl http://localhost:$port 2>&1 | grep -q Connection.refused
}

function checkPortFree {
  port=$1
  if ! isPortFree $port; then 
    fatal "== FATAL: port $port already in use"
  fi
}

function startProcess {
  retpid=$1
  shift
  cmd="$@"
  $cmd & eval $retpid=$!
}

checkPortFree 8545
checkPortFree 3000

startProcess gethpid /usr/local/bin/geth --dev --verbosity 1
echo pid=$gethpid

exit

function bgLauncher {
  port=$1
  name=$2
  shift; shift
  cmd="$*"
  test -z "$cmd" && fatal "usage: bgLauncher {port} {name} {cmd...}"

  if ! isPortFree $port; then 
    fatal "== FATAL: cannot start $name: port $port in use."
  fi

  echo == starting $name

  $cmd & ID=$!

  trap "echo == killing $name; kill -9 $ID" EXIT

  echo == waiting for $name on port $port
  while isPortFree $port; do sleep 1; done
  echo == started $name
}


GETH="/usr/local/bin/geth  --dev \
      --http.port ${PORT:=8545} \
      --nousb \
      --miner.gaslimit 12000000 \
      --http \
      --http.api personal,eth,net,web3,debug \
      --allow-insecure-unlock \
      --rpc.allow-unprotected-txs \
      --http.vhosts '*,localhost,host.docker.internal' \
      --http.corsdomain '*' \
      --http.addr "0.0.0.0" \
      --dev \
      --nodiscover --maxpeers 0 --mine \
      --miner.threads 1 \
      --verbosity 2 \
      --networkid ${NETWORKID:=1337} \
      --allow-insecure-unlock \
      --http \
      --verbosity 1 \
      --ignore-legacy-receipts"

bgLauncher 8545 geth $GETH
sleep 1
