# docker-compose configuration to bring up a bunder.
# configuration is found in $(PWD)/workdir/bundler.config.json
# You must have the following environment variable set in .env file:
#  HOST            | my.example.com   | Bundler rpc host address
#  DEFAULT_EMAIL   | me@example.com   | Your e-mail for LetsEncrypt to send SSL alerts to

version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "10"

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

  bundler:
    container_name:   bundler
    ports: [ '3000:3000' ]
    image: accountabstraction/bundler:0.5.0
    restart: on-failure

    volumes:
      - ./workdir:/app/workdir:ro

    environment:
      url: https://${HOST}/
      LETSENCRYPT_HOST: $HOST
      LETSENCRYPT_PORT: 3000
      VIRTUAL_HOST: $HOST
      VIRTUAL_PATH: /
      VIRTUAL_DEST: /
    mem_limit: 300M
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "10"

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
